### PR TITLE
1.0 to master

### PR DESCRIPTION
**Pull request by grawk**
did some branch maintenance, and want to PR 1.0 into master.. 0.x already moved to `0.x-release` branch

### CODE REVIEW

**Comment by nikulkarni** [comment]
Looks good and it seems the last travis build passed, however I still see "Merge with caution" message?

**Comment by grawk** [comment]
Starting the node@0.11 job again. Assuming arbitrary failure but stay tuned

**Comment by grawk** [comment]
Looks good now

**Comment by nikulkarni** [comment]
:+1:

**Pull request merged**
