### PR TITLE
Rewritten mkdirRecursive

### PR DESCRIPTION
**Pull request by kotsie**

### CODE REVIEW

**Comment by aredridel** [comment]
Any reason not to just use the [mkdirp](https://www.npmjs.com/package/mkdirp) package? `mkdirp.sync` is this behavior.

**Comment by kotsie** [comment]
nope, just did not think to pull a package for this, but it can definitely be replaced

**Comment by kotsie** [comment]
can you please merge this one and we can replace it with a library later down the line? right now this is blocking some of the folks from using it

**Comment by aredridel** [comment]
There's a build failure. That's gotta get fixed first.

**Comment by aredridel** [comment]
:+1:

**Comment by grawk** [comment]
@kotsie I've merged and published this as `v1.0.3`. Please can you share your name/email if you would like to be in the contributors block of package.json? Thanks!

**Comment by grawk** [comment]
@aredridel thanks for helping with this PR!

**Comment by kotsie** [comment]
@grawk My name is Ilia Smyshlaev, and email ismyshlaev@paypalcorp.com

**Pull request merged**
